//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HAC.Domain.Tools;

namespace HAC.Domain
{
    using System;

    public partial class Announcement
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public string DescriptionNoHTML
        {
            get { return TextTools.StripHtmlTagByCharArray(Description); }
        }

        public string DescriptionShort
        {
            get { return DescriptionNoHTML.Substring(0, DescriptionNoHTML.Length > 150 ? 150 : DescriptionNoHTML.Length); }
        }

        public System.DateTime CreateDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string ExpiryDateForDisplay
        {
            get
            {
                return this.ExpiryDate.ToString("d");
            }

        }

        public string ExpiryDateForEdit
        {
            get
            {
                return this.ExpiryDate.ToString("yyyy-MM-dd");
            }

            set { ExpiryDate = DateTime.Parse(value); }
        }
        public System.DateTime LastModified { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> PhotoImageId { get; set; }
        public Nullable<int> PhotoCategoryId { get; set; }
    }
}
