//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string subject { get; set; }
        public Nullable<int> Day { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string show_news { get; set; }
        public string news1 { get; set; }
        public string news2 { get; set; }
        public Nullable<int> resultid { get; set; }
        public byte[] photo { get; set; }
        public string ImgS { get; set; }
        public string ImgB { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<int> mid { get; set; }
        public string show_results { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
    }
}
