//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HACEntities : DbContext
    {
        public HACEntities()
            : base("name=HACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Member> Members { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<link> links { get; set; }
        public DbSet<membership> memberships { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<result> results { get; set; }
        public DbSet<pic_categories> pic_categories { get; set; }
        public DbSet<pic_groups> pic_groups { get; set; }
        public DbSet<pic_images> pic_images { get; set; }
    }
}
