//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int Id { get; set; }
        public string category { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte[] image { get; set; }
        public string mid { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public byte[] photo { get; set; }
    }
}
