//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public int ID { get; set; }
        public string lname { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string dob { get; set; }
        public string type { get; set; }
        public Nullable<int> mid { get; set; }
        public string access { get; set; }
        public Nullable<int> ex1 { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public Nullable<System.DateTime> renew { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
    }
}
