//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class pic_images
    {
        public int PIC_ID { get; set; }
        public int PIC_CAT { get; set; }
        public string PIC_NAME { get; set; }
        public string PIC_IMAGE { get; set; }
        public string PIC_HEIGHT { get; set; }
        public string PIC_WIDTH { get; set; }
        public Nullable<int> PIC_VIEW { get; set; }
        public Nullable<System.DateTime> PIC_DATED { get; set; }
        public Nullable<int> PIC_APPROVED { get; set; }
        public string PIC_DESC { get; set; }
    
        public virtual pic_categories pic_categories { get; set; }
    }
}
