//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public Nullable<int> mid { get; set; }
        public string type { get; set; }
        public string membership { get; set; }
        public string gender { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string Email { get; set; }
        public string subject { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string best { get; set; }
        public string ambitions { get; set; }
        public string latest { get; set; }
        public string tip { get; set; }
        public string position { get; set; }
        public string standard { get; set; }
        public string qualifications { get; set; }
        public string specialisation { get; set; }
        public string posts_held { get; set; }
        public string current_athletes { get; set; }
        public string athletes_achievements { get; set; }
        public string age_group { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> pb { get; set; }
        public Nullable<int> result { get; set; }
        public string pb1 { get; set; }
        public string pb2 { get; set; }
        public byte[] weeman { get; set; }
        public Nullable<bool> more { get; set; }
        public string more2 { get; set; }
    }
}
